name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        sudo apt-get install -y chromium-browser
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
        python -m pip install pytest requests webdriver-manager selenium
        python -m pip install .
    - name: Run test
      run: python -m pytest tests/